### ISSUE TITLE
Error when interaction model is specified with fixed effects for all variables and interaction.

### ISSUE THREAD

**Issue by AngCamp** [lhe17/nebula#27] opened 2023-06-23 20:16 UTC
I tried two different models to model an interaction effect in an experiment I pulled from online but the properly specified model matrix produces an error.

When I specify the model only with an interaction term like so.  It fits properly and neubula gives me results etc etc..
`dkkl1.nebula.mm = model.matrix(~Condition:Label, data=pred.df)`

But notice in the design matrix there is no effect for Condition or Lable on their own.  So this is not a desirable model.
```
A matrix: 6 x 9 of type dbl
(Intercept)	ConditionContext-Only:LabeltdT+	ConditionFear-Only:LabeltdT+	ConditionFear-Recall:LabeltdT+	ConditionHomecage:LabeltdT+	ConditionContext-Only:LabeltdT-	ConditionFear-Only:LabeltdT-	ConditionFear-Recall:LabeltdT-	ConditionHomecage:LabeltdT-
1	1	0	0	0	0	0	0	0	1
2	1	0	0	0	0	0	0	0	1
3	1	0	0	0	0	0	0	0	1
4	1	0	0	0	0	0	0	0	1
5	1	0	0	0	0	1	0	0	0
6	1	0	0	0	0	1	0	0	0
```

The model really should be like so...

`dkkl1.nebula.mm = model.matrix(~Condition*Label, data=pred.df)`

Giving the following design matrix...

```
  | (Intercept) | ConditionFear-Only | ConditionFear-Recall | ConditionHomecage | LabeltdT- | ConditionFear-Only:LabeltdT- | ConditionFear-Recall:LabeltdT- | ConditionHomecage:LabeltdT-
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 0 | 0 | 1 | 1 | 0 | 0 | 1
1 | 0 | 0 | 1 | 1 | 0 | 0 | 1
1 | 0 | 0 | 1 | 1 | 0 | 0 | 1
1 | 0 | 0 | 1 | 1 | 0 | 0 | 1
1 | 0 | 0 | 0 | 1 | 0 | 0 | 0
1 | 0 | 0 | 0 | 1 | 0 | 0 | 0
```

But when I fit this model it returns an error:

```
results.dkkl1.nebula <- nebula(dkkl1_nebula_g$count, dkkl1_nebula_g$id,
                               pred=dkkl1_nebula_g$pred, ncore=2)
```

```

Remove  357  genes having low expression.
Analyzing  14170  genes with  19  subjects and  1164  cells.
Error in {: task 13129 failed - "missing value where TRUE/FALSE needed"
Traceback:

1. nebula(dkkl1_nebula_g$count, dkkl1_nebula_g$id, pred = dkkl1_nebula_g$pred, 
 .     ncore = 2)
2. foreach(i = gid, .combine = "cbind") %dorng% {
 .     posv = call_posindy(count, i - 1, nind)
 .     if ((posv$mct * mfs) < 3) {
 .         ord = 3
```

There is more but I can't post the full message here as it is very very long.  Any idea what has gone wrong?  I don't think the first formulation is the proper way to find the interaction effects, which is a problem because that's what I'm interested in.

**Comment by lhe17** [comment] 2023-06-23 20:45
Hi AngCamp,

To replicate and investigate the problem, could you let me know where I can
get this dataset online or could you share your count matrix
(dkkl1_nebula_g$count), the sample id (dkkl1_nebula_g$id) and pred.df with
me?

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-06-23 20:52
I can email you the data, the online data doesn't have the cell type labels.  I had to reproduce their results myself.  How can I share it with you?

**Comment by lhe17** [comment] 2023-06-23 20:55
Hi AngCamp,

You could either send it to this email address ***@***.***) as an
attachment or put it on a cloud drive like dropbox or google drive and
share the link with me.

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-06-23 21:18
Google drive: https://drive.google.com/drive/folders/1DLkDWhQ1i73OeSJkT2l-mk1yEWPxaGQZ?usp=sharing

You will have to change the file paths, also provided the protien coding genes from ensemble I use for gene filtering.  Here is the code I'm using to load the dataframes and run the analysis.


```
chencounts.path <- '~/PavLabEngrams/EngramCellClassifier/Chen2020_GSE152632/GSE152632_GEO_mberkchen_TRAP2_counts.csv.gz'
chenmeta.path <- '~/PavLabEngrams/EngramCellClassifier/Chen2020_GSE152632/SraRunTable.txt'
protcodinglist.path <- "/home/acampbell/PavLabEngrams/IEG_gradients/unique_stablestranscriptIDs_m39_gene_names.txt"
```


```
#Chen
chen2020_counts <- read.csv(chencounts.path, header = TRUE)
rownames(chen2020_counts) <- chen2020_counts$X
chen2020_counts <- chen2020_counts[,2:3531]
chen2020_meta <- read.csv( chenmeta.path , header = TRUE)

#add engram label
chen2020_meta$engram_label <-  as.factor(sapply(as.character(colnames(chen2020_counts)), function(y) if (grepl("_pos_", y, fixed=TRUE)) "tdT+" else "tdT-"))

#create the condition label
condition_label <- chen2020_meta$source_name %>%
  sapply( function(y) if (grepl("Homecage", y, fixed=TRUE)) "Homecage")

condition_label <- chen2020_meta$source_name
condition_label[str_detect(condition_label, "Homecage")] = "Homecage"
condition_label[str_detect(condition_label, "Context-Only")] = "Context-Only"
condition_label[str_detect(condition_label, "Fear-Only")] = "Fear-Only"
condition_label[str_detect(condition_label, "Fear-Recall")] = "Fear-Recall"
chen2020_meta$condition_label <- condition_label

#adding cell bacrcodes from coutn data to rows of metadata for seurat
rownames(chen2020_meta) <- colnames(chen2020_counts)


chen2020_meta <- cbind(chen2020_meta, read.csv(chenclsutermarkers.formeta.path) )
```

```
# pull the dkkl1 neurons
dkkl1.idx <- chen2020_meta$ChenLayerMarkers=='Dkkl1'

dkkl1.counts.df <- chen2020_counts[,dkkl1.idx]
#dkkl1.counts.df <- data.frame(t(dkkl1.counts.df))
#rownames(dkkl1.counts.df) <- colnames(chen2020_counts)[dkkl1.idx]
#colnames(dkkl1.counts.df) <- rownames(chen2020_counts)
dim(dkkl1.counts.df)

```
```
# gene filtering
chen.genefilter <- rowSums(chen2020_counts > 0) >= 10 # removes about 3k genes, use it later (not at cell level)
chen.cellfilter <- (colSums(chen2020_counts) > 50000) | (colSums(chen2020_counts > 0) >= 100)
prot.coding.genes.ensmlble.df <- read.csv(protcodinglist.path)
mouse.prot.coding.genes <- unique(prot.coding.genes.ensmlble.df$Gene.name)

dkkl1.counts.df <- dkkl1.counts.df[chen.cellfilter,]
dkkl1.counts.df <- dkkl1.counts.df[rownames(dkkl1.counts.df) %in%  mouse.prot.coding.genes,]
dim(dkkl1.counts.df)
```



```
# make prediction matrix
pred.df <- data.frame(Condition = chen2020_meta$condition_label[dkkl1.idx],
                     Label = chen2020_meta$engram_label[dkkl1.idx])
pred.df$Condition <- as.factor(pred.df$Condition)
pred.df$Label <- as.factor(pred.df$Label)

# put it in the list
#dkkl1_nebula$pred <- pred.df

# make this offset thing
dkkl1_nebula$offset <- rep(1, length(dkkl1_nebula$id))
```

```
# make the model and fit it
dkkl1.nebula.mm = model.matrix(~Condition*Label, data=pred.df)
dim(dkkl1.nebula.mm)
head(dkkl1.nebula.mm)
```


```
dkkl1_nebula_g <- group_cell(count=dkkl1_nebula$count, 
                             id=dkkl1_nebula$id,
                             pred=dkkl1.nebula.mm)

dkkl1_nebula_g$offset <- dkkl1_nebula$offset
```

```
results.dkkl1.nebula <- nebula(dkkl1_nebula_g$count, dkkl1_nebula_g$id,
                               pred=dkkl1_nebula_g$pred, ncore=2)
```

**Comment by lhe17** [comment] 2023-06-23 21:44
Hi Angus,

Thank you.
I downloaded the files you shared, but was not able to replicate
the problem because I do not have the file
"chenclsutermarkers.formeta.path", which I suppose contains the cell type
information. In addition, I do not have the object 'dkkl1_nebula', which
contains the mouse IDs. To share it with me, you can just save this object
to an RData file using the script
save(dkkl1_nebula, file='dkkl1_nebula.RData')

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-06-26 22:19
Hi sorry about that.  The .csv has been uploaded to the drive link I shared earlier.  It is `Chen2020_ClusterMarkers.csv`.

**Comment by AngCamp** [comment] 2023-06-27 18:07
I also updated the script.  You will still need to set the file path for "chenclsutermarkers.formeta.path".

**Comment by lhe17** [comment] 2023-06-27 18:36
Hi Angus,

Thank you.
I received the .csv file for the clusters.
I'm still waiting for your mouse IDs (i.e., dkkl1_nebula$id). Could you
please save "dkkl1_nebula$id" to a csv file and upload it as well?

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-06-27 22:26
The mouse Id is in the meta data, I realized I was missing some code I have updated the code blocks above it should work now.

**Comment by AngCamp** [comment] 2023-06-30 19:13
In case you didn't see I added this line, which previously was missing before.  `dkkl1_nebula$id <- chen2020_meta$source_name[dkkl1.idx]`

**Comment by AngCamp** [comment] 2023-06-30 19:22
I have uploaded the R object for you, at the google drive https://drive.google.com/drive/folders/1DLkDWhQ1i73OeSJkT2l-mk1yEWPxaGQZ?usp=sharing 

It is the file "dkkl1_nebula.RData"   Sorry for all the trouble I wanted to make sure my code for creating the object was fine as well.

**Comment by lhe17** [comment] 2023-06-30 19:37
Hi Angus,

Thank you for your additional information.
I followed your scripts, but I fail to replicate the error you reported. I
get the results and do not see any errors on my machine.
In order to replicate your error, could you please upload your object
"dkkl1_nebula_g"
that you used as the direct input for nebula?
In addition, it would be better to use a cell-specific scaling factor such
as the library size rather than one. This can be easily obtained using
dkkl1_nebula_g$offset <- colSums(dkkl1_nebula_g$count) # calculate the
library size of each cell
I tested using this scaling factor, and found that the cell overdispersion
of most genes drops substantially. Also, fewer genes failed convergence
when using the library size as the scaling factor.

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-06-30 20:22
Ok thanks for the tip.  I have fixed the offset issue.  Sorry in the tutorial it's not clear that offset is library size, its also confusing because in the sample data object you provide the offset is just a vector of ones so it's not clear what it's meant to be.  I reuploaded the dffl1_nebula_g object with the offset as library size.

You should see the following: 

`> str(dkkl1_nebula_g)`

```
List of 4
 $ count :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:7345331] 0 2 5 7 8 9 11 12 14 16 ...
  .. ..@ p       : int [1:1165] 0 7004 15021 21855 28984 35885 42876 49418 53451 56694 ...
  .. ..@ Dim     : int [1:2] 14527 1164
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:14527] "0610009B22Rik" "0610010K14Rik" "0610012G03Rik" "0610030E20Rik" ...
  .. .. ..$ : chr [1:1164] "B1_T6_K7_S83_mouse1" "D6_T3_H15_S91_mouse1" "E3_T6_A10_S146_mouse1" "B7_T6_A8_S144_mouse1" ...
  .. ..@ x       : num [1:7345331] 35 48 103 4 27 11 29 16 9 182 ...
  .. ..@ factors : list()
 $ id    : num [1:1164] 1 1 1 1 1 1 1 1 1 1 ...
 $ pred  : num [1:1164, 1:8] 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:1164] "1" "2" "3" "4" ...
  .. ..$ : chr [1:8] "(Intercept)" "ConditionContext-Only" "ConditionFear-Only" "ConditionFear-Recall" ...
 $ offset: Named num [1:14527] 92932 4974 152132 14623 3459 ...
  ..- attr(*, "names")= chr [1:14527] "0610009B22Rik" "0610010K14Rik" "0610012G03Rik" "0610030E20Rik" ...
```

**Comment by AngCamp** [comment] 2023-06-30 20:28
The error has changed but I still get one.

```
results.dkkl1.nebula <- nebula(dkkl1_nebula_g$count, dkkl1_nebula_g$id,
                               pred=dkkl1_nebula_g$pred, ncore=2)
```

Returns...

```
Remove  357  genes having low expression.
Analyzing  14170  genes with  19  subjects and  1164  cells.
Warning message in sqrt(re_all[, i]):
"NaNs produced"
Warning message in sqrt(re_all[, i]):
"NaNs produced"
Warning message in sqrt(re_all[, i]):
"NaNs produced"
Warning message in sqrt(re_all[, i]):
"NaNs produced"
Warning message in sqrt(re_all[, i]):
"NaNs produced"
Warning message in sqrt(re_all[, i]):
"NaNs produced"
Warning message in sqrt(re_all[, i]):
"NaNs produced"
Warning message in sqrt(re_all[, i]):
"NaNs produced"
```


And when I run summary, `summary(results.dkkl1.nebula)`  I get....

```
               Length Class      Mode     
summary           26  data.frame list     
overdispersion     2  data.frame list     
convergence    14170  -none-     numeric  
algorithm      14170  -none-     character
covariance         0  -none-     NULL     
random_effect      0  -none-     NULL   
```

**Comment by AngCamp** [comment] 2023-06-30 20:29
Could you possibly just share the results object you get with me if we can't get this to work?  I am running this on my lab server through a jupyter notebook with an R kernel.  That could be causing the issue.

**Comment by AngCamp** [comment] 2023-06-30 20:31
Oh never mind I'm getting genes and fits out of it.

**Comment by AngCamp** [comment] 2023-06-30 20:33
Is there anything else I need to consider?  Or do you think the issue is solved?  It looks good to me.

**Comment by lhe17** [comment] 2023-06-30 20:41
Hi Angus,

To use the library size as the offset, you should run the following.
re <-
nebula(dkkl1_nebula_g$count,dkkl1_nebula_g$id,pred=dkkl1_nebula_g$pred,offset=colSums(dkkl1_nebula_g$count))

In addition, the offset in your "dkkl1_nebula_g" is the row sums, not
column sums.

I tried both offsets (one or the library size) and neither gave me an
error. I guess some settings in the R environment might cause the issue.
Could you please run sessionInfo() on your machine for me and let me know
your R environment? I want to investigate this issue.

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-06-30 20:50
Certainly, running.... 

`>  sessionInfo()`

Returns....

```
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/acampbell/miniconda3/envs/pavlab-engrams/lib/libopenblasp-r0.3.21.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] nebula_1.4.1         scrime_1.3.5         compositions_2.0-5  
 [4] FactoMineR_2.7       factoextra_1.0.7     tictoc_1.0.1        
 [7] edgeR_3.36.0         limma_3.50.3         lme4_1.1-30         
[10] Matrix_1.5-3         dplyr_1.0.9          data.table_1.14.6   
[13] caret_6.0-92         lattice_0.20-45      pheatmap_1.0.12     
[16] Dict_0.1.0           ggplot2_3.4.1        pROC_1.18.0         
[19] caTools_1.18.2       sampler_0.2.4        stringr_1.4.1       
[22] rfUtilities_2.1-5    randomForest_4.7-1.1

loaded via a namespace (and not attached):
  [1] minqa_1.2.4          colorspace_2.1-0     ggsignif_0.6.3      
  [4] class_7.3-20         estimability_1.4.1   IRdisplay_1.1       
  [7] base64enc_0.1-3      farver_2.1.1         ggpubr_0.4.0        
 [10] listenv_0.8.0        ggrepel_0.9.1        DT_0.26             
 [13] prodlim_2019.11.13   fansi_1.0.4          mvtnorm_1.1-3       
 [16] lubridate_1.8.0      codetools_0.2-18     splines_4.1.3       
 [19] leaps_3.1            robustbase_0.95-0    IRkernel_1.3        
 [22] jsonlite_1.8.1       nloptr_2.0.3         broom_1.0.1         
 [25] cluster_2.1.3        compiler_4.1.3       backports_1.4.1     
 [28] emmeans_1.8.3        assertthat_0.2.1     RcppZiggurat_0.1.6  
 [31] fastmap_1.1.0        cli_3.4.1            htmltools_0.5.3     
 [34] tools_4.1.3          gtable_0.3.2         glue_1.6.2          
 [37] reshape2_1.4.4       doRNG_1.8.6          Rcpp_1.0.10         
 [40] carData_3.0-5        vctrs_0.5.1          nlme_3.1-159        
 [43] iterators_1.0.14     timeDate_4021.106    tensorA_0.36.2      
 [46] gower_1.0.0          globals_0.16.1       trust_0.1-8         
 [49] lifecycle_1.0.3      rngtools_1.5.2       rstatix_0.7.0       
 [52] future_1.32.0        DEoptimR_1.0-11      MASS_7.3-58.1       
 [55] scales_1.2.1         ipred_0.9-13         parallel_4.1.3      
 [58] RColorBrewer_1.1-3   rpart_4.1.16         reshape_0.8.8       
 [61] stringi_1.7.6        foreach_1.5.2        hardhat_1.2.0       
 [64] boot_1.3-28          lava_1.6.10          repr_1.1.4          
 [67] rlang_1.1.0          pkgconfig_2.0.3      bitops_1.0-7        
 [70] evaluate_0.16        purrr_0.3.4          labeling_0.4.2      
 [73] recipes_1.0.1        htmlwidgets_1.5.4    Rfast_2.0.7         
 [76] tidyselect_1.2.0     parallelly_1.35.0    plyr_1.8.8          
 [79] magrittr_2.0.3       R6_2.5.1             generics_0.1.3      
 [82] multcompView_0.1-8   pbdZMQ_0.3-7         DBI_1.1.2           
 [85] pillar_1.8.1         withr_2.5.0          abind_1.4-5         
 [88] survival_3.4-0       scatterplot3d_0.3-42 nnet_7.3-18         
 [91] tibble_3.1.8         future.apply_1.9.1   bayesm_3.1-5        
 [94] car_3.1-0            crayon_1.5.2         uuid_1.0-4          
 [97] utf8_1.2.3           doFuture_1.0.0       locfit_1.5-9.7      
[100] grid_4.1.3           ModelMetrics_1.2.2.2 digest_0.6.29       
[103] flashClust_1.01-2    xtable_1.8-4         tidyr_1.2.1         
[106] stats4_4.1.3         munsell_0.5.0     
```

**Comment by AngCamp** [comment] 2023-06-30 21:02
Also is there a way to get the effects of the random subject effects and their genes?  I know estimating p-values for these is complicated but is that information stored in the nebula results anywhere?

**Comment by lhe17** [comment] 2023-06-30 21:14
Hi Angus,

Yes, you can run nebula with output_re=TRUE. Then you will see the random
effects in the output$random_effect.

In addition, I need to mention and revise in the next version that
those genes with NaN in their summary statistics have a convergence issue
and should not be reported or used for downstream analysis. This is not
very common, but I do see it happens to two genes in your data.

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-06-30 21:30
I filtered those genes out myself using...

```
 dkkl1.nebula.re <- na.omit(dkkl1.nebula.re)
dim(dkkl1.nebula.re)
```

I lose about 400 genes total doing this, down to 13773  from 14170.  na.omit drops any row with an na in one of it's columns.

**Comment by AngCamp** [comment] 2023-06-30 21:57
When using  output_re=TRUE, does the `nebularesutlsobj$random_effect` dataframe contain effect sizes or p-values?  What are the se effects? Like..` se_(Intercept)`.

**Comment by AngCamp** [comment] 2023-06-30 23:59
I know calculating p-values for random effects is difficult or non-standard.

**Comment by lhe17** [comment] 2023-07-01 12:14
Hi Angus,

The nebularesutlsobj$random_effect data frame are η described in the
manuscript. You can think of it as a kind of effect size, not p-values.
P-values are not available for random effects.
se_* are the standard errors of the logFC.

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-07-03 22:33
Sorry one last thing, some of the logFC are unrealistically high.  I am interested in the "ConditionFear-Recall:Labeltd+" interaction and after corrective for multiple testing (BH) and thresholding at an FDR of 0.05.  It leaves me with the follwoing genes as DEGs.  This is all fine but the effect sizes for a couple genes are unrealistically high, _Mical1_ has a -345 logFC and _Lad1_ has a logFC of 3417.  The sequencing depth in the cell was 1.5 million reads on average, there shouldn't be enough molecules in the reaction to produce that kind of increase.  I'm worried I didn't do my preprocessing correctly.

To be clear I don't expect there to be any differential expression and a few genes is fine.

```
<html>
<body>
<!--StartFragment-->

gene | logFC_ConditionFear-Recall:LabeltdT+
-- | --

Atp5e | -0.6478018
Bola2 | -1.1239726
Chchd1 | -0.9904798
Mical1 | -345.0644655
Mrpl14 | -1.3159953
Mrpl23 | -1.0134296
Naa38 | -1.0657664
Ndufa12 | -0.8239315
Ndufb9 | -0.7021679
Pomt1 | 3.5986447
Rad51 | 6.4909405
Selenos | -1.4402919
Lad1 | 3417.2111347

<!--EndFragment-->
</body>
</html>
```

**Comment by lhe17** [comment] 2023-07-04 19:33
Hi Angus,

Thank you very much for your questions and feedback. I highly appreciate
them.
I really like the data that you are analyzing because the data quality is
so poor (due to PCR duplicates) that it triggers some bugs in nebula that
are rarely seen in general 10x data sets.

I investigated this issue carefully. So, let 's first talk about those
sigificant genes with a very large logFC you reported. There is no problem
with those large logFCs (we will talk about them later) but their
significant p-values turn out to be a bug related to numerial precision.
Generally, the standard errors for those large logFCs should be even larger
(thus the p-values should be very close to one), but some logFCs in your
data are so large that some errors occur due to the numerial precision when
inversing the Hessian matrix to calculate the p-values. The remedy is that
I will upload an updated version (v1.4.2) in one or two days in which this
bug will be fixed. In the updated version, you can remove problematic genes
with a convergence code <= -20.

Second, you might be curious why there are so many genes with very large
logFCs in your results. The cause is separation (
https://en.wikipedia.org/wiki/Separation_(statistics)), which I also
mentioned in a previous thread (https://github.com/lhe17/nebula/issues/18).
It usually happens to an unbalanced binary variable (let's say A=0/1) when
the sample size is small. The problem is, for example, if all the cells
with A=1 has zero counts, the maximum likelihood estimate (MLE) of logFC of
A will be minus infinity because the probability of observing a count in
cells with A=1 is 0=exp(minus infinity). In this case, as you can see, the
MLE fails. The logFCs in the results are not exactly infinity because the
optimization procedure stops before reaching infinity due to the numerical
cutoff.

Third, you might wonder how to mitigate, avoid or resolve this issue in
your case. One option can be reducing the number of dummy variables in the
design matrix. For example, you investigated the interaction effects of all
four levels of Condition simultaneously in one model, which is ambitious.
You might test them one by one. For example, you might first test the
interaction effect of Context-Only. Then you will have only four binary
variables in the model, which are
Intercept, ConditionContext-Only, LabeltdT+,
and ConditionContext-Only:LabeltdT+. I found that the number of genes with
the separation issue dropped from ~1300 to ~200 compared to the model with
all eight variables. In the long run, I'm considering resolving this issue
by providing some solutions in a future version.

Best regards,
Liang

**Comment by lhe17** [comment] 2023-07-05 09:47
Hi Angus,

Following my previous comment, the new version 1.4.2 is now available on
github and can be installed.

Best regards,
Liang

**Comment by AngCamp** [comment] 2023-07-05 19:28
HI Liang,

Thank you these comments are extremely helpful for me.  I am also glad that you have been enjoying working with the data.  The paper they are from made some very bold claims and in the process of working with it for my thesis I came across several issues.  I will take your point about the model to light, I will reduce the condition to two variables Fear-Recall and Control (which will encompass the other three conditions).  That should simplify the design matrix and reduce a fitting error while keeping all the data.  The study had 3 controls and really they are not interested in the other conditions.

With regards to the PCR duplicates what in the data could I point toa s being evidence of this?  We also suspect based on the gene expression we are seeing that the cells have become stressed during sorting and are dying (a little bit).

I will update the nebula package thank you.

Regards Angus.

**Comment by AngCamp** [comment] 2023-07-05 20:01
Also installing the new version of nebula resulted in a non-zero exit status.  It is likely because on our server we have not gone past a certain version of C++ (which is currently on C++17), so some of the dependencies for nebula 1.4.2 are themselves outdated because of this.  Very common packages like Rfast and tibble are affected.  Its not in my hands to control this, I have pushed our lab to upgrade it on our servers for months but so far it has not been done.  So for now I will have to use nebula v1.2.2.  I wouldn't worry about these error messages too much, I think most people will have upgraded their C++ library.

I tried installing it on Rstudio with `devtools::install_github("lhe17/nebula")`

I wont post the full error message, this is the key issue:

`Error: C++17 standard requested but CXX17 is not defined`

Now running `devtools::install_github("lhe17/nebula")` in an R kernel on Jupyter results in....

```
Downloading GitHub repo lhe17/nebula@HEAD

digest       (0.6.29     -> 0.6.32    ) [CRAN]
parallelly   (1.35.0     -> 1.36.0    ) [CRAN]
listenv      (0.8.0      -> 0.9.0     ) [CRAN]
globals      (0.16.1     -> 0.16.2    ) [CRAN]
future       (1.32.0     -> 1.33.0    ) [CRAN]
RcppGSL      (0.3.12     -> 0.3.13    ) [CRAN]
vctrs        (0.5.1      -> 0.6.3     ) [CRAN]
pillar       (1.8.1      -> 1.9.0     ) [CRAN]
tibble       (3.1.8      -> 3.2.1     ) [CRAN]
fs           (1.5.2      -> 1.6.2     ) [CRAN]
waldo        (0.4.0      -> 0.5.1     ) [CRAN]
rlang        (1.1.0      -> 1.1.1     ) [CRAN]
ps           (1.7.1      -> 1.7.5     ) [CRAN]
processx     (3.7.0      -> 3.8.2     ) [CRAN]
pkgload      (1.3.0      -> 1.3.2     ) [CRAN]
jsonlite     (1.8.1      -> 1.8.7     ) [CRAN]
evaluate     (0.16       -> 0.21      ) [CRAN]
cli          (3.4.1      -> 3.6.1     ) [CRAN]
callr        (3.7.2      -> 3.7.3     ) [CRAN]
future.apply (1.9.1      -> 1.11.0    ) [CRAN]
RcppArmad... (0.11.2.3.1 -> 0.12.4.1.0) [CRAN]
RcppEigen    (0.3.3.9.2  -> 0.3.3.9.3 ) [CRAN]
testthat     (3.1.4      -> 3.1.9     ) [CRAN]
Rfast        (2.0.7      -> 2.0.8     ) [CRAN]
Installing 24 packages: digest, parallelly, listenv, globals, future, RcppGSL, vctrs, pillar, tibble, fs, waldo, rlang, ps, processx, pkgload, jsonlite, evaluate, cli, callr, future.apply, RcppArmadillo, RcppEigen, testthat, Rfast

Warning message in i.p(...):
"installation of package 'rlang' had non-zero exit status"
Warning message in i.p(...):
"installation of package 'cli' had non-zero exit status"
Warning message in i.p(...):
"installation of package 'vctrs' had non-zero exit status"
Warning message in i.p(...):
"installation of package 'Rfast' had non-zero exit status"
Warning message in i.p(...):
"installation of package 'tibble' had non-zero exit status"
Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

   During startup - Warning messages:
   1: Setting LC_CTYPE failed, using "C" 
   2: Setting LC_TIME failed, using "C" 
   3: Setting LC_MESSAGES failed, using "C" 
   4: Setting LC_MONETARY failed, using "C" 
   5: Setting LC_PAPER failed, using "C" 
   6: Setting LC_MEASUREMENT failed, using "C" 
v  checking for file '/tmp/RtmpuNGrBa/remotesfd367233c7c5/lhe17-nebula-2fa23d4/DESCRIPTION'
-  preparing 'nebula':
v  checking DESCRIPTION meta-information
-  cleaning src
-  installing the package to process help pages
-  saving partial Rd database (34.5s)
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'nebula_1.4.2.tar.gz'
   

Warning message in i.p(...):
"installation of package '/tmp/RtmpuNGrBa/filefd365e5b0891/nebula_1.4.2.tar.gz' had non-zero exit status"
```

The other packages are having a non-zero exit status because of the C++ issue.  You can see several very commonly used packages are out of date on our server because of it.

**Comment by lhe17** [comment] 2023-07-06 13:19
Hi Angus,

Yes, nebula requires Rfast, which requires C++17.
I also submitted the new version (1.4.2) to CRAN and you might be able to
install it from there once it is approved.

Regarding the PCR duplicates, you can see that from the cell-level
overdispersion. Generally, scRNA-seq techniques with UMI to remove PCR
duplicates have very small (<1) cell-level overdispersion for most genes.
But this data set has many genes with a cell-level overdispersion >100. And
if you look at the counts, you see that many genes have 100+ counts in only
a couple of cells while 99.5% of the cells have zero counts. This is
typically seen in scRNA-seq data sets such as SMART-seq2 that do not employ
UMI to remove PCR duplicates.

Best regards,
Liang

**Closed** 2023-07-07 05:51 UTC
